### ISSUE TITLE
context.update and context.globalUpdate mixed up in notes

### ISSUE THREAD

**Issue by fuzetsu** [isiahmeadows/mithril.js#5]
`context.globalUpdate` is described as:
> This schedules a subtree redraw, not a root-level redraw.

and `context.update` is described as:
> This schedules a global redraw.

In `core.md`

https://github.com/isiahmeadows/mithril.js/blob/v3-design/core.md

**Comment by dead-claudia** [comment]
Fixed by just removing it altogether.
